const fs = require('fs');
const path = require('path');

// Helper to safely extract metrics from nested or flat schema structures
function getMetricValue(metricObj, ...keys) {
  if (!metricObj) return 0;
  for (const key of keys) {
    // Check nested structure (e.g. metricObj.values.avg)
    if (metricObj.values && typeof metricObj.values === 'object' && key in metricObj.values) {
      return metricObj.values[key];
    }
    // Check flat structure (e.g. metricObj.avg)
    if (key in metricObj) {
      return metricObj[key];
    }
  }
  return 0;
}

function run() {
  // Resolve paths for summary.json (look in current dir, then parent, then specific subdirs)
  const pathsToTry = [
    path.join(process.cwd(), 'summary.json'),
    path.join(process.cwd(), 'BrainBattleBackend', 'summary.json'),
    path.join(__dirname, '..', 'summary.json'),
    path.join(__dirname, 'summary.json')
  ];

  let rawData = null;
  let filePathUsed = '';

  for (const p of pathsToTry) {
    if (fs.existsSync(p)) {
      try {
        rawData = fs.readFileSync(p, 'utf8');
        filePathUsed = p;
        break;
      } catch (e) {
        console.warn(`Warning: Could not read file at ${p}: ${e.message}`);
      }
    }
  }

  if (!rawData) {
    console.error('Error: Could not locate or read summary.json in any of the expected locations.');
    process.exit(1);
  }

  let summaryData;
  try {
    summaryData = JSON.parse(rawData);
  } catch (e) {
    console.error(`Error: Failed to parse summary.json as JSON: ${e.message}`);
    process.exit(1);
  }

  const metrics = summaryData.metrics || {};

  // Extract metrics using the defensive getMetricValue helper
  const totalRequests = getMetricValue(metrics.http_reqs, 'count');
  const rps = getMetricValue(metrics.http_reqs, 'rate');
  const avgResponse = getMetricValue(metrics.http_req_duration, 'avg');
  const minResponse = getMetricValue(metrics.http_req_duration, 'min');
  const maxResponse = getMetricValue(metrics.http_req_duration, 'max');
  const p95Response = getMetricValue(metrics.http_req_duration, 'p(95)');
  
  // k6 rates are returned as float ratios (0.0 to 1.0)
  const failureRate = getMetricValue(metrics.http_req_failed, 'value', 'rate') * 100;
  const assertionRate = getMetricValue(metrics.checks, 'value', 'rate') * 100;

  // Format values nicely
  const formattedRps = Number(rps).toFixed(2);
  const formattedAvg = Number(avgResponse).toFixed(2);
  const formattedMin = Number(minResponse).toFixed(2);
  const formattedMax = Number(maxResponse).toFixed(2);
  const formattedP95 = Number(p95Response).toFixed(2);
  const formattedFailureRate = Number(failureRate).toFixed(2);
  const formattedAssertionRate = Number(assertionRate).toFixed(2);

  // Generate the Markdown output
  const markdownReport = `
### 📈 API Load Test Performance Summary

| Metric | Value | Description |
| :--- | :--- | :--- |
| **Total Requests** | ${totalRequests.toLocaleString()} | Total requests executed during the test |
| **Throughput (RPS)** | **${formattedRps}** req/sec | Average number of requests handled per second |
| **Average Response Time** | ${formattedAvg} ms | The mean time taken for responses |
| **Minimum Response Time** | ${formattedMin} ms | The fastest response received |
| **Maximum Response Time** | ${formattedMax} ms | The slowest response received |
| **95th Percentile (p95)** | **${formattedP95}** ms | 95% of requests completed under this duration |
| **Request Failure Rate** | ${formattedFailureRate}% | Percentage of failed HTTP requests (Target: < 5%) |
| **Checks Pass Rate** | ${formattedAssertionRate}% | Percentage of status code 200 checks passed |

---
*Generated by BrainBattle Backend k6 Load Tester.*
`;

  // Output to GITHUB_STEP_SUMMARY if available
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (summaryFile) {
    try {
      fs.appendFileSync(summaryFile, markdownReport);
      console.log(`Successfully appended k6 load test results to GITHUB_STEP_SUMMARY: ${summaryFile}`);
    } catch (e) {
      console.error(`Error: Failed to write to GITHUB_STEP_SUMMARY: ${e.message}`);
    }
  } else {
    console.log('GITHUB_STEP_SUMMARY environment variable not set. Printing report to console:');
    console.log(markdownReport);
  }
}

run();
